title: "Room for God & Others"
description: "Essays, poems, thoughts, sayings, and voices."
url: "https://gregconradismith.github.io"
baseurl: "/room-for-god-and-others"
lang: en
timezone: America/New_York
css_version: 15

analytics:
  plausible_domain: ""
  plausible_src: "https://plausible.io/js/script.js"

author:
  name: "Greg Conrad Smith"

collections:
  essays:
    output: true
    permalink: /essays/:title/
  poems:
    output: true
    permalink: /poetry/:name/
  sayings:
    output: true
    permalink: /sayings/:name/
  quotes:
    output: true
    permalink: /voices/:name/
  thoughts:
    output: true
    permalink: /thoughts/:name/

defaults:
  - scope:
      path: ""
      type: essays
    values:
      layout: essay
      category: essay
  - scope:
      path: ""
      type: poems
    values:
      layout: poem
  - scope:
      path: ""
      type: sayings
    values:
      layout: saying
  - scope:
      path: ""
      type: quotes
    values:
      layout: quote
  - scope:
      path: ""
      type: thoughts
    values:
      layout: thought

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-seo-tag
  - jekyll-feed
